[source.crates-io]
replace-with = "rsproxy-sparse"

[source.cernet]
registry = "sparse+https://mirrors.cernet.edu.cn/crates.io-index/"

[source.rsproxy-sparse]
registry = "sparse+https://rsproxy.cn/index/"